### ISSUE TITLE
Test integration server certificate setup

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/das2go#47] opened 2022-10-05 15:54 UTC
Please test DAS against the integration Rucio server

rucio_host = http://cms-rucio-int.cern.ch
auth_host = https://cms-rucio-auth-int.cern.ch

(same as the normal server except with -int added). However this server does not have much data in it and is not a replacement for the full Rucio server, so this should not be user visible. All we need to test is whether the Go DAS client can successfully authenticate against the server(s).

Eric

**Comment by vkuznet** [comment] 2022-10-07 12:57
@ericvaandering , could you please provide me more content on how tokens should be used. What I need is an example using curl to access your Rucio URLs using IAM token.

For instance, I took a token we get on k8s and run the following command:
```
t=....
curl -s -L -k -H "X-Rucio-Auth-Token: $t" http://cms-rucio-int.cern.ch/replicas/list -H "content-type: application/json" -d '{"all_states": false, "domain": null, "rse_expression": "T2_CH_CERN", "resolve_archives": false, "resolve_parents": false, "dids": [{"scope": "cms", "name": "/SingleElectron/Run2012D-v1/RAW"}]}'
# and I got this output
{"ExceptionClass": "CannotAuthenticate", "ExceptionMessage": "Cannot authenticate with given credentials"}
```

What I need from you is working example where you'll show me how you obtain your token and how you'll use it with Rucio URLs. Since Rucio may require specific token, e.g. some scopes, please outline full procedure how to obtain valid token which will be accepted by Rucio servers.

**Comment by ericvaandering** [comment] 2022-10-07 16:44
This ticket doesn't have anything to do with IAM tokens. That's another issue we'll need to work on together. Nothing would "just work" right now.

What I would like you to try to accessing Rucio-int now the exact way you access the production Rucio today to test whether my changes to how the X509 CA certificates are handled break DAS.

For instance, here is the list of datasets at Nebraska in that server:

```
[ewv@lxplus8s05 rucio]$ rucio list-datasets-rse T2_US_Nebraska
SCOPE:NAME
----------
cms:/RelValTTbar_14TeV/CMSSW_12_1_0_pre3-121X_mcRun3_2021_realistic_v2-v1/DQMIO#c94c53dd-cb0b-4752-8ded-99defaf02920
cms:/RelValTTbar_14TeV/CMSSW_12_1_0_pre3-121X_mcRun3_2021_realistic_v2-v1/GEN-SIM#1ccd410d-bdf9-4f5e-8f03-ecc68113b6dc
cms:/RelValTTbar_14TeV/CMSSW_12_1_0_pre3-121X_mcRun3_2021_realistic_v2-v1/GEN-SIM-DIGI-RAW#7fbe226d-1e8c-4501-9a7c-9042590ac97d
cms:/RelValTTbar_14TeV/CMSSW_12_1_0_pre3-121X_mcRun3_2021_realistic_v2-v1/GEN-SIM-RECO#d7e29ee9-7724-4af8-9564-2fca2e2c71a8
```

**Comment by vkuznet** [comment] 2022-10-07 17:09
Sorry, I thought we need IAM tokens. Said that, please provide curl command syntax since I have no idea how rucio client works.

Here is what I do. I have the following bash script (I call it `rucio_curl`):
```
#!/bin/bash

aurl=https://cms-rucio-auth.cern.ch/auth/x509
aurl=https://cms-rucio-auth-int.cern.ch/auth/x509

url=$1
#echo "$url"
opt="-s -L -k --key $HOME/.globus/userkey.pem --cert $HOME/.globus/usercert.pem"
token=`curl $opt -v $aurl 2>&1 | grep "X-Rucio-Auth-Token:" | sed -e "s,< X-Rucio-Auth-Token: ,,g"`
# echo "$token"
curl $opt -H "X-Rucio-Auth-Token: $token" "$url"
```
and if I run it with `aurl=https://cms-rucio-auth.cern.ch/auth/x509` (part of the script I got correct result:
```
rucio_curl http://cms-rucio.cern.ch/replicas/cms/RelValTTbar_14TeV/CMSSW_12_1_0_pre3-121X_mcRun3_2021_realistic_v2-v1/DQMIO#c94c53dd-cb0b-4752-8ded-99defaf02920
{"scope": "cms", "name": "/store/relval/CMSSW_12_1_0_pre3/RelValTTbar_14TeV/DQMIO/121X_mcRun3_2021_realistic_v2-v1/10000/80951186-1B0D-11EC-8663-95BCE183BEEF.root", "bytes": 116833537, "md5": null, "adler32": "ad761f0f", "pfns": {"davs://eoscms.cern.ch:443/eos/cms/store/relval/CMSSW_12_1_0_pre3/RelValTTbar_14TeV/DQMIO/121X_mcRun3_2021_realistic_v2-v1/10000/80951186-1B0D-11EC-8663-95BCE183BEEF.root": {"rse_id": "542ab69d82bf401e9218bbe375bb1fce", "rse": "T2_CH_CERN", "type": "DISK", "volatile": false, "domain": "wan", "priority": 1, "client_extract": false}}, "rses": {"T2_CH_CERN": ["davs://eoscms.cern.ch:443/eos/cms/store/relval/CMSSW_12_1_0_pre3/RelValTTbar_14TeV/DQMIO/121X_mcRun3_2021_realistic_v2-v1/10000/80951186-1B0D-11EC-8663-95BCE183BEEF.root"]}, "states": {"T2_UA_KIPT": "AVAILABLE", "T2_CH_CERN": "AVAILABLE"}}
```
But if I use `aurl=https://cms-rucio-auth-int.cern.ch/auth/x509`  in it and run it I got the exception:
```
rucio_curl http://cms-rucio-int.cern.ch/replicas/cms/RelValTTbar_14TeV/CMSSW_12_1_0_pre3-121X_mcRun3_2021_realistic_v2-v1/DQMIO#c94c53dd-cb0b-4752-8ded-99defaf02920
{"ExceptionClass": "CannotAuthenticate", "ExceptionMessage": "Cannot authenticate with given credentials"}
```
So, you do not need DAS to test your rucio servers, just use curl as shown above and fix the problem on your end.

**Comment by ericvaandering** [comment] 2022-10-07 18:00
That's not true. As I mentioned, somehow the Go version of DAS is very particular (much more so than curl) about the CA certificates used to verify it's certificate and we needed to add CRLs to the servers and a cron job to make DAS happy. 

So even your curl test above is not sufficient to verify DAS will work against the integration server. I need you to test the DAS client itself.

What DN are you using? I noticed production Rucio has a bunch of DNs for DAS and integration only had your personal one. I added `/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=cmswebmi/CN=430796/CN=Robot: CMS Web Service account` which is the one I suspect you are using. 

Also, to make your script more accurate you should add "X-Rucio-Account: das" as another header. But like I said, this script will work where DASGo will fail.

**Comment by vkuznet** [comment] 2022-10-07 18:21
So far curl does not work and I don't waste time on coding until I make curl working. I'm using my personal certificate in test, and I added your header too `X-Rucio-Account: das`, so far results are the same, i.e. using int urls I can't make curl to work. Can you use this curl script and try yourself and how me that it is working? And, I tried both at my local network and from CERN one.

**Comment by vkuznet** [comment] 2022-10-07 18:23
Here is my certificate DN:
```
    Signature Algorithm: sha512WithRSAEncryption
        Issuer: DC=ch, DC=cern, CN=CERN Grid Certification Authority
        Validity
            Not Before: Mar 30 12:56:24 2022 GMT
            Not After : Apr 22 11:20:16 2023 GMT
        Subject: DC=ch, DC=cern, OU=Organic Units, OU=Users, CN=valya, CN=443502, CN=Valentin Y Kuznetsov
```
and, as I wrote it works with production rucio URLs, but does not with int using curl script I shared. So, it tells me that so far the issue is at your end on int URLs since it does not accept my DN/cert.

**Comment by ericvaandering** [comment] 2022-10-07 18:48
OK, the curl script works fine for me except that I could not get the shell script (probably quoting issue) to give me a token either for myself or the root account. However, the curl command itself works fine:
```
[ewv@lxplus8s05 ~]$ curl -s -L -k -H "X-Rucio-Account: ewv" --key /tmp/x509up_u2910 --cert /tmp/x509up_u2910 -v https://cms-rucio-auth-int.cern.ch/auth/x509 2>&1 | grep Token
< Access-Control-Expose-Headers: X-Rucio-Auth-Token
< X-Rucio-Auth-Token: ewv-/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ewv/CN=644876/CN=Eric Wayne Vaandering-unknown-ab7427f969b048599b1146aeb89ceee2
< X-Rucio-Auth-Token-Expires: Fri, 07 Oct 2022 19:42:45 UTC
[ewv@lxplus8s05 ~]$ curl -s -L -k --key /tmp/x509up_u2910 --cert /tmp/x509up_u2910 -v https://cms-rucio-auth-int.cern.ch/auth/x509 2>&1 | grep Token
< Access-Control-Expose-Headers: X-Rucio-Auth-Token
< X-Rucio-Auth-Token: root-/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ewv/CN=644876/CN=Eric Wayne Vaandering-unknown-e0387b1b29e048a4a91124716795a0e7
< X-Rucio-Auth-Token-Expires: Fri, 07 Oct 2022 19:42:56 UTC
```
Your cert should allow you access to the DAS account:
```
[ewv@lxplus8s05 ~]$ rucio-admin account list-identities das
Identity: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=cmswebmi/CN=430796/CN=Robot: CMS Web Service account,     type: X509
Identity: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=valya/CN=443502/CN=Valentin Y Kuznetsov,  type: X509
```
or the valya account. So you should be able to do as I did above with both account=valya and account=das.

As an even simpler test I would suggest:

```
./rucio_curl http://cms-rucio-int.cern.ch/accounts/whoami 
root-/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ewv/CN=644876/CN=Eric Wayne Vaandering-unknown-526d1e2fac974819bd20b9499f29ee06
{"account_type": "SERVICE", "email": null, "deleted_at": null, "updated_at": "2021-04-19T19:47:31", "status": "ACTIVE", "suspended_at": null, "created_at": "2021-04-19T19:47:31", "account": "root"}
```

**Comment by ericvaandering** [comment] 2022-10-07 18:48
(Of course, as you see above, I use a proxy but that should have no impact)

**Comment by ericvaandering** [comment] 2022-10-07 19:04
> it works with production rucio URLs, but does not with int using curl script I shared. So, it tells me that so far the issue is at your end on int URLs since it does not accept my DN/cert.

Rucio also has a mechanism to try to convert DN into a preferred account name, but I suspect this is not working or working differently for you DN/account combinations, so it would help if you checked with the raw CURL as above and then got rucio_curl to be explicit about which account you want to use.

**Comment by vkuznet** [comment] 2022-10-07 20:15
Erik, I fixed curl approach and now it works. Then, I tried DAS with the following:
```
RUCIO_ACCOUNT=das RUCIO_URL=http://cms-rucio-int.cern.ch RUCIO_AUTH_URL=https://cms-rucio-auth-int.cern.ch ./dasgoclient -query="site block=/RelValTTbar_14TeV/CMSSW_12_1_0_pre3-121X_mcRun3_2021_realistic_v2-v1/DQMIO#c94c53dd-cb0b-4752-8ded-99defaf02920" -verbose
```
it seems to be working, but I get mixed results, some times it is working but other times it is not. Here is relevant part which acquire token:
```
2022/10/07 16:04:06 http response rurl https://cms-rucio-auth-int.cern.ch/auth/x509, dump HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: None
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: None
Access-Control-Expose-Headers: X-Rucio-Auth-Token
Cache-Control: no-cache, no-store, max-age=0, must-revalidate, post-check=0, pre-check=0
Connection: Keep-Alive
Content-Type: application/octet-stream
Date: Fri, 07 Oct 2022 20:04:06 GMT
Keep-Alive: timeout=5, max=128
Pragma: no-cache
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/4.7.1 Python/3.6
X-Rucio-Auth-Token: das-/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=valya/CN=443502/CN=Valentin Y Kuznetsov-unknown-006341df6e1142a89ef5f57939eb083e
X-Rucio-Auth-Token-Expires: Fri, 07 Oct 2022 21:04:06 UTC
X-Rucio-Host: cms-rucio-auth-int.cern.ch
Content-Length: 0
```
As you can see the call to auth server is going fine. This works on my laptop, and when I changed das maps to use int rucio url I see that my requests pass through. I think DAS is fine now with your URLs.

**Comment by ericvaandering** [comment] 2022-10-07 20:20
Great. But what's not working all the time? Are you getting responses from either the auth server or the regular server other than a 200?

**Comment by vkuznet** [comment] 2022-10-07 21:04
No, I think everything is fine, but I found that my code needs adjustment when I supply external RUCIO_URL env since it reads rucio urls from DAS maps and apply token to cms-rucio, rather the cms-rucio-int. In this case it does not work since token was generated at int instance, while was used in prod one. I'll address this separately.

**Comment by ericvaandering** [comment] 2022-10-07 21:20
Yes, that's true for sure. Thanks for looking at this Valentin. 

We'll get this setting into production next week or the week after.

**Comment by vkuznet** [comment] 2022-10-28 19:08
@ericvaandering can I close this issue now?

**Closed** 2022-10-28 19:11 UTC
